import {chromium} from 'playwright';
const base=process.argv[2]||'http://localhost:8790';if(!base.startsWith('http://localhost:'))throw Error('Usa instancia local aislada');const key=process.env.ADMIN_KEY;if(!key)throw Error('ADMIN_KEY requerida');
const slug='soporte-'+Date.now().toString(36);const headers={'content-type':'application/json','x-admin-key':key};const r=await fetch(base+'/api/admin/tenants/create',{method:'POST',headers,body:JSON.stringify({name:'Negocio soporte',owner:'Carlos',slug,email:'test@example.com',password:'original123',pin:'2468',business_type:'bar',catalog:'sample'})});const created=await r.json();if(!r.ok)throw Error(JSON.stringify(created));const id=created.tenant.id;
const browser=await chromium.launch();try{
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/admin.html');await p.fill('#admin-key',key);await p.locator('#login button').click();await p.locator('#plans').waitFor({state:'visible'});await p.fill('#client-search',slug);await p.getByRole('button',{name:'Editar',exact:true}).click();await p.selectOption('#business-type','fruteria');if(!await p.locator('[name=module_weight]').isChecked()||await p.locator('[name=module_tables]').isChecked())throw Error('Funciones del giro incorrectas');await p.getByRole('button',{name:'Guardar cliente',exact:true}).click();await p.locator('#list').getByText(slug,{exact:false}).waitFor();await p.getByRole('link',{name:'Ver POS',exact:true}).click();await p.locator('#content .card').first().waitFor();if(await p.locator('#content .card').count()!==18)throw Error('Catálogo cambiado');await p.getByRole('button',{name:'Funciones',exact:true}).click();await p.getByText('Mesas · Desactivada',{exact:true}).waitFor();await p.screenshot({path:'test-results/support-functions.png'});await p.getByRole('link',{name:'← Volver al panel de clientes',exact:true}).click();await p.locator('#plans').waitFor({state:'visible'});await p.fill('#client-search',slug);await p.getByRole('button',{name:'Contraseña',exact:true}).click();await p.fill('#new-password','nueva1234');await p.fill('#repeat-password','nueva1234');await p.getByRole('button',{name:'Guardar contraseña',exact:true}).click();await p.locator('.modal').waitFor({state:'detached'});
const pos=await context.newPage();await pos.goto(base);await pos.getByText('Conectar este dispositivo',{exact:true}).click();await pos.fill('[name=slug]',slug);await pos.locator('[data-act=toggle-pass]').click();await pos.fill('[name=email]','test@example.com');await pos.fill('[name=password]','nueva1234');await pos.click('#go');await pos.waitForSelector('.user-tile');await pos.locator('.user-tile').filter({hasText:'Carlos'}).click();for(const n of '2468')await pos.locator(`[data-k="${n}"]`).click();await pos.waitForSelector('.pos .card');
await p.getByRole('button',{name:'Usuarios y dispositivos',exact:true}).click();await p.locator('#refresh-monitor').waitFor();await p.click('#refresh-monitor');await p.getByText('Usuario reportado: Carlos',{exact:false}).waitFor();await p.screenshot({path:'test-results/support-monitor.png'});
await pos.locator('.user-btn').click();await pos.getByRole('button',{name:'Cerrar sesión en este dispositivo',exact:true}).click();await pos.waitForSelector('.user-tile');await p.click('#refresh-monitor');await p.getByText('Sin usuario seleccionado',{exact:false}).waitFor();await p.setViewportSize({width:375,height:812});if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Monitoreo móvil desbordado');await p.screenshot({path:'test-results/support-monitor-mobile.png'});
if(errors.length)throw Error(errors.join('\n'));console.log('OK: giro y funciones, catálogo conservado, Ver POS, contraseña, actividad reportada y cierre de usuario.');
}finally{await browser.close();}
